In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas

df1 = pandas.read_excel('/content/drive/MyDrive/KPMG_VI_New_raw_data_update_final (1).xlsx', sheet_name='Transactions')
df1.columns = df1.iloc[0]
df1 = df1[1:]
# print whole sheet data
print(df1)

0     transaction_id product_id customer_id     transaction_date online_order  \
1                  1          2        2950  2017-02-25 00:00:00        False
2                  2          3        3120  2017-05-21 00:00:00         True
3                  3         37         402  2017-10-16 00:00:00        False
4                  4         88        3135  2017-08-31 00:00:00        False
5                  5         78         787  2017-10-01 00:00:00         True
...              ...        ...         ...                  ...          ...
19996          19996         51        1018  2017-06-24 00:00:00         True
19997          19997         41         127  2017-11-09 00:00:00         True
19998          19998         87        2284  2017-04-14 00:00:00         True
19999          19999          6        2764  2017-07-03 00:00:00        False
20000          20000         11        1144  2017-09-22 00:00:00         True

0     order_status           brand product_line product_class product_size  \
1         Approved           Solex     Standard        medium       medium
2         Approved   Trek Bicycles     Standard        medium        large
3         Approved      OHM Cycles     Standard           low       medium
4         Approved  Norco Bicycles     Standard        medium       medium
5         Approved  Giant Bicycles     Standard        medium        large
...            ...             ...          ...           ...          ...
19996     Approved      OHM Cycles     Standard          high       medium
19997     Approved           Solex         Road        medium       medium
19998     Approved      OHM Cycles     Standard        medium       medium
19999     Approved      OHM Cycles     Standard          high       medium
20000     Approved   Trek Bicycles     Standard        medium        small

0     list_price standard_cost product_first_sold_date
1          71.49         53.62                   41245
2        2091.47        388.92                   41701
3        1793.43        248.82                   36361
4        1198.46         381.1                   36145
5         1765.3        709.48                   42226
...          ...           ...                     ...
19996    2005.66        1203.4                   37823
19997     416.98        312.74                   35560
19998     1636.9         44.71                   40410
19999     227.88        136.73                   38216
20000    1775.81       1580.47                   36334

[20000 rows x 13 columns]

In [ ]:
df1.head()

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
1,1,2,2950,2017-02-25 00:00:00,False,Approved,Solex,Standard,medium,medium,71.49,53.62,41245
2,2,3,3120,2017-05-21 00:00:00,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701
3,3,37,402,2017-10-16 00:00:00,False,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361
4,4,88,3135,2017-08-31 00:00:00,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.1,36145
5,5,78,787,2017-10-01 00:00:00,True,Approved,Giant Bicycles,Standard,medium,large,1765.3,709.48,42226

In [ ]:
df2 = pandas.read_excel('/content/drive/MyDrive/KPMG_VI_New_raw_data_update_final (1).xlsx', sheet_name='CustomerDemographic')
df2.columns = df2.iloc[0]
df2 = df2[1:]
# print whole sheet data
print(df2)

0    customer_id      first_name  last_name  gender  \
1              1         Laraine  Medendorp       F
2              2             Eli    Bockman    Male
3              3           Arlin     Dearle    Male
4              4          Talbot        NaN    Male
5              5  Sheila-kathryn     Calton  Female
...          ...             ...        ...     ...
3996        3996         Rosalia   Halgarth  Female
3997        3997          Blanch     Nisuis  Female
3998        3998          Sarene    Woolley       U
3999        3999       Patrizius        NaN    Male
4000        4000           Kippy    Oldland    Male

0    past_3_years_bike_related_purchases                  DOB  \
1                                     93  1953-10-12 00:00:00
2                                     81  1980-12-16 00:00:00
3                                     61  1954-01-20 00:00:00
4                                     33  1961-10-03 00:00:00
5                                     56  1977-05-13 00:00:00
...                                  ...                  ...
3996                                   8  1975-08-09 00:00:00
3997                                  87  2001-07-13 00:00:00
3998                                  60                  NaN
3999                                  11  1973-10-24 00:00:00
4000                                  76  1991-11-05 00:00:00

0                  job_title job_industry_category     wealth_segment  \
1        Executive Secretary                Health      Mass Customer
2     Administrative Officer    Financial Services      Mass Customer
3         Recruiting Manager              Property      Mass Customer
4                        NaN                    IT      Mass Customer
5              Senior Editor                   NaN  Affluent Customer
...                      ...                   ...                ...
3996   VP Product Management                Health      Mass Customer
3997         Statistician II         Manufacturing     High Net Worth
3998       Assistant Manager                    IT     High Net Worth
3999                     NaN         Manufacturing  Affluent Customer
4000    Software Engineer IV                   NaN  Affluent Customer

0    deceased_indicator                                            default  \
1                     N                                                 "'
2                     N                       <script>alert('hi')</script>
3                     N                                2018-02-01 00:00:00
4                     N  () { _; } >_[$($())] { touch /tmp/blns.shellsh...
5                     N                                                NIL
...                 ...                                                ...
3996                  N                                               -100
3997                  N                                           â¦testâ§
3998                  N                                                NaN
3999                  N                             Â¡â¢Â£Â¢âÂ§Â¶â¢ÂªÂºââ
4000                  N                                                0/0

0    owns_car tenure
1         Yes     11
2         Yes     16
3         Yes     15
4          No      7
5         Yes      8
...       ...    ...
3996       No     19
3997      Yes      1
3998       No    NaN
3999      Yes     10
4000       No     11

[4000 rows x 13 columns]

In [ ]:
df2.head()

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,default,owns_car,tenure
1,1,Laraine,Medendorp,F,93,1953-10-12 00:00:00,Executive Secretary,Health,Mass Customer,N,"""'",Yes,11
2,2,Eli,Bockman,Male,81,1980-12-16 00:00:00,Administrative Officer,Financial Services,Mass Customer,N,<script>alert('hi')</script>,Yes,16
3,3,Arlin,Dearle,Male,61,1954-01-20 00:00:00,Recruiting Manager,Property,Mass Customer,N,2018-02-01 00:00:00,Yes,15
4,4,Talbot,NaN,Male,33,1961-10-03 00:00:00,NaN,IT,Mass Customer,N,() { _; } >_[$($())] { touch /tmp/blns.shellsh...,No,7
5,5,Sheila-kathryn,Calton,Female,56,1977-05-13 00:00:00,Senior Editor,NaN,Affluent Customer,N,NIL,Yes,8

In [ ]:
df3 = pandas.read_excel('/content/drive/MyDrive/KPMG_VI_New_raw_data_update_final (1).xlsx', sheet_name='CustomerAddress')
df3.columns = df3.iloc[0]
df3 = df3[1:]
# print whole sheet data
print(df3)

0    customer_id                    address postcode            state  \
1              1         060 Morning Avenue     2016  New South Wales
2              2        6 Meadow Vale Court     2153  New South Wales
3              4         0 Holy Cross Court     4211              QLD
4              5        17979 Del Mar Point     2448  New South Wales
5              6           9 Oakridge Court     3216              VIC
...          ...                        ...      ...              ...
3995        3999            1482 Hauk Trail     3064              VIC
3996        4000  57042 Village Green Point     4511              QLD
3997        4001     87 Crescent Oaks Alley     2756              NSW
3998        4002           8194 Lien Street     4032              QLD
3999        4003            320 Acker Drive     2251              NSW

0       country property_valuation
1     Australia                 10
2     Australia                 10
3     Australia                  9
4     Australia                  4
5     Australia                  9
...         ...                ...
3995  Australia                  3
3996  Australia                  6
3997  Australia                 10
3998  Australia                  7
3999  Australia                  7

[3999 rows x 6 columns]

In [ ]:
df3.head()

,customer_id,address,postcode,state,country,property_valuation
1,1,060 Morning Avenue,2016,New South Wales,Australia,10
2,2,6 Meadow Vale Court,2153,New South Wales,Australia,10
3,4,0 Holy Cross Court,4211,QLD,Australia,9
4,5,17979 Del Mar Point,2448,New South Wales,Australia,4
5,6,9 Oakridge Court,3216,VIC,Australia,9

In [ ]:
df4 = pandas.read_excel('/content/drive/MyDrive/KPMG_VI_New_raw_data_update_final (1).xlsx', sheet_name='NewCustomerList')
df4.columns = df4.iloc[0]
df4 = df4[1:]
# print whole sheet data
print(df4)

0    first_name  last_name  gender past_3_years_bike_related_purchases  \
1       Chickie    Brister    Male                                  86
2         Morly     Genery    Male                                  69
3       Ardelis  Forrester  Female                                  10
4        Lucine      Stutt  Female                                  64
5       Melinda     Hadlee  Female                                  34
...         ...        ...     ...                                 ...
996   Ferdinand  Romanetti    Male                                  60
997        Burk    Wortley    Male                                  22
998    Melloney      Temby  Female                                  17
999      Dickie    Cubbini    Male                                  30
1000      Sylas    Duffill    Male                                  56

0                     DOB                     job_title job_industry_category  \
1              1957-07-12               General Manager         Manufacturing
2              1970-03-22           Structural Engineer              Property
3     1974-08-28 00:00:00        Senior Cost Accountant    Financial Services
4              1979-01-28    Account Representative III         Manufacturing
5              1965-09-21             Financial Analyst    Financial Services
...                   ...                           ...                   ...
996            1959-10-07                     Paralegal    Financial Services
997            2001-10-17        Senior Sales Associate                Health
998            1954-10-05  Budget/Accounting Analyst IV    Financial Services
999            1952-12-17             Financial Advisor    Financial Services
1000           1955-10-02           Staff Accountant IV              Property

0        wealth_segment deceased_indicator owns_car  ... state    country  \
1         Mass Customer                  N      Yes  ...   QLD  Australia
2         Mass Customer                  N       No  ...   NSW  Australia
3     Affluent Customer                  N       No  ...   VIC  Australia
4     Affluent Customer                  N      Yes  ...   QLD  Australia
5     Affluent Customer                  N       No  ...   NSW  Australia
...                 ...                ...      ...  ...   ...        ...
996   Affluent Customer                  N       No  ...   NSW  Australia
997       Mass Customer                  N       No  ...   NSW  Australia
998   Affluent Customer                  N      Yes  ...   QLD  Australia
999       Mass Customer                  N      Yes  ...   QLD  Australia
1000      Mass Customer                  N      Yes  ...   NSW  Australia

0    property_valuation   NaN     NaN       NaN       NaN     NaN  Rank  \
1                     6  0.56  0.7000  0.875000  0.743750     1.0     1
2                    11  0.89  0.8900  1.112500  0.945625     1.0     1
3                     5  1.01  1.0100  1.010000  1.010000     1.0     1
4                     1  0.87  1.0875  1.087500  1.087500     4.0     4
5                     9  0.52  0.5200  0.650000  0.650000     4.0     4
...                 ...   ...     ...       ...       ...     ...   ...
996                   7  0.79  0.7900  0.790000  0.790000   996.0   996
997                  10  0.76  0.7600  0.950000  0.807500   997.0   997
998                   2  0.85  1.0625  1.062500  1.062500   997.0   997
999                   2  1.09  1.3625  1.362500  1.158125   997.0   997
1000                  9  0.47  0.5875  0.734375  0.624219  1000.0  1000

0        Value
1      1.71875
2      1.71875
3      1.71875
4     1.703125
5     1.703125
...        ...
996      0.374
997      0.357
998      0.357
999      0.357
1000      0.34

[1000 rows x 23 columns]

In [ ]:
df4.head()

,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,...,state,country,property_valuation,NaN,NaN,NaN,NaN,NaN,Rank,Value
1,Chickie,Brister,Male,86,1957-07-12,General Manager,Manufacturing,Mass Customer,N,Yes,...,QLD,Australia,6,0.56,0.7000,0.8750,0.743750,1.0,1,1.71875
2,Morly,Genery,Male,69,1970-03-22,Structural Engineer,Property,Mass Customer,N,No,...,NSW,Australia,11,0.89,0.8900,1.1125,0.945625,1.0,1,1.71875
3,Ardelis,Forrester,Female,10,1974-08-28 00:00:00,Senior Cost Accountant,Financial Services,Affluent Customer,N,No,...,VIC,Australia,5,1.01,1.0100,1.0100,1.010000,1.0,1,1.71875
4,Lucine,Stutt,Female,64,1979-01-28,Account Representative III,Manufacturing,Affluent Customer,N,Yes,...,QLD,Australia,1,0.87,1.0875,1.0875,1.087500,4.0,4,1.703125
5,Melinda,Hadlee,Female,34,1965-09-21,Financial Analyst,Financial Services,Affluent Customer,N,No,...,NSW,Australia,9,0.52,0.5200,0.6500,0.650000,4.0,4,1.703125

In [ ]:
df1.describe()

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
count,20000,20000,20000,20000,19640,20000,19803,19803,19803,19803,20000.00,19803.00,19803
unique,20000,101,3494,364,2,2,6,4,3,3,296.00,103.00,100
top,1,0,2183,2017-02-14 00:00:00,True,Approved,Solex,Standard,medium,medium,2091.47,388.92,33879
freq,1,1378,14,82,9829,19821,4253,14176,13826,12990,465.00,465.00,234

In [ ]:
df2.describe()

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,default,owns_car,tenure
count,4000,4000,3875,4000,4000,3913,3494,3344,4000,4000,3698,4000,3913
unique,4000,3139,3725,6,100,3448,195,9,3,2,90,2,22
top,1,Max,Pristnor,Female,16,1978-01-30 00:00:00,Business Systems Development Analyst,Manufacturing,Mass Customer,N,100,Yes,7
freq,1,5,3,2037,56,7,45,799,2000,3998,113,2024,235

In [ ]:
df3.describe()

,customer_id,address,postcode,state,country,property_valuation
count,3999,3999,3999,3999,3999,3999
unique,3999,3996,873,5,1,12
top,1,3 Mariners Cove Terrace,2170,NSW,Australia,9
freq,1,2,31,2054,3999,647

In [ ]:
df4.describe()

0              NaN          NaN          NaN          NaN          NaN
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.747340     0.839005     0.942673     0.870514   498.819000
std       0.205082     0.248858     0.294832     0.280891   288.810997
min       0.400000     0.400000     0.400000     0.340000     1.000000
25%       0.570000     0.637500     0.712500     0.658750   250.000000
50%       0.750000     0.820000     0.912500     0.842625   500.000000
75%       0.920000     1.031875     1.142969     1.062500   750.250000
max       1.100000     1.375000     1.718750     1.718750  1000.000000

In [ ]:
import pandas as pd
df5 = pd.merge(df1, df3, on=["customer_id"])
df5

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date,address,postcode,state,country,property_valuation
0,1,2,2950,2017-02-25 00:00:00,False,Approved,Solex,Standard,medium,medium,71.49,53.62,41245,984 Hoepker Court,3064,VIC,Australia,6
1,11065,1,2950,2017-10-16 00:00:00,False,Approved,Giant Bicycles,Standard,medium,medium,1403.5,954.82,37659,984 Hoepker Court,3064,VIC,Australia,6
2,18923,62,2950,2017-04-26 00:00:00,False,Approved,Solex,Standard,medium,medium,478.16,298.72,40487,984 Hoepker Court,3064,VIC,Australia,6
3,2,3,3120,2017-05-21 00:00:00,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701,4 Shopko Circle,2196,NSW,Australia,5
4,6862,4,3120,2017-10-05 00:00:00,False,Approved,Giant Bicycles,Standard,high,medium,1129.13,677.48,40649,4 Shopko Circle,2196,NSW,Australia,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19963,19854,68,130,2017-02-02 00:00:00,True,Approved,OHM Cycles,Standard,medium,medium,1636.9,44.71,40410,58 Helena Hill,2205,New South Wales,Australia,7
19964,17966,17,2789,2017-12-06 00:00:00,False,Approved,Solex,Standard,high,medium,1024.66,614.8,35378,724 West Park,2112,NSW,Australia,11
19965,18462,80,2789,2017-06-20 00:00:00,False,Approved,OHM Cycles,Touring,low,medium,1073.07,933.84,42226,724 West Park,2112,NSW,Australia,11
19966,17981,69,3446,2017-12-26 00:00:00,True,Approved,Giant Bicycles,Road,medium,medium,792.9,594.68,33879,8 Becker Drive,4868,QLD,Australia,4
19967,18165,86,3446,2017-12-03 00:00:00,False,Approved,OHM Cycles,Standard,medium,medium,235.63,125.07,38206,8 Becker Drive,4868,QLD,Australia,4

In [ ]:
df2['job_title'].value_counts()

Business Systems Development Analyst    45
Tax Accountant                          44
Social Worker                           44
Internal Auditor                        42
Recruiting Manager                      41
                                        ..
Database Administrator I                 4
Health Coach I                           3
Health Coach III                         3
Research Assistant III                   3
Developer I                              1
Name: job_title, Length: 195, dtype: int64

In [ ]:
df4['job_title'].value_counts()

Associate Professor         15
Environmental Tech          14
Software Consultant         14
Chief Design Engineer       13
Assistant Manager           12
                            ..
Accountant II                1
Programmer IV                1
Administrative Officer       1
Accounting Assistant III     1
Web Developer I              1
Name: job_title, Length: 184, dtype: int64